# Codex Zsh autocompletion plugin
# Supports intelligent completion for codex commands, including subcommands and parameters

# Main completion function
_codex() {
    local curcontext="$curcontext" state line
    typeset -A opt_args

    local -a commands codex_opts

    # Define main commands (based on codex --help)
    commands=(
        'exec:Run Codex non-interactively'
        'login:Manage login'
        'logout:Remove stored authentication credentials'
        'mcp:Run Codex as MCP server and manage MCP servers'
        'mcp-server:Run Codex MCP server (stdio transport)'
        'app-server:Run application server or related tools'
        'completion:Generate shell completion scripts'
        'sandbox:Run commands in Codex-provided sandbox'
        'apply:Apply latest diff generated by Codex agent to local working tree'
        'resume:Resume previous interactive session'
        'cloud:Browse tasks in Codex Cloud and apply changes locally'
        'features:Check feature flags'
        'help:Display help information'
    )

    # Codex common options (based on codex --help)
    codex_opts=(
        '-c:Override config value (key=value format)'
        '--config:Override config value (key=value format)'
        '--enable:Enable feature (repeatable)'
        '--disable:Disable feature (repeatable)'
        '-i:Optional image to attach to initial prompt'
        '--image:Optional image to attach to initial prompt'
        '-m:Model that agent should use'
        '--model:Model that agent should use'
        '--oss:Use local Ollama server'
        '-h:Show help'
        '--help:Show help'
    )

    _arguments -C \
        {-c,--config}'[Override config value]:config:' \
        {-h,--help}'[Show help]' \
        '1: :->command' \
        '*::arg:->args'

    case $state in
        command)
            _describe -t commands 'codex commands' commands
            ;;
        args)
            case $line[1] in
                mcp)
                    _codex_mcp
                    ;;
                app-server)
                    _codex_app_server
                    ;;
                apply)
                    _codex_apply
                    ;;
                cloud)
                    _codex_cloud
                    ;;
                completion)
                    _codex_completion
                    ;;
                exec)
                    _codex_exec
                    ;;
                features)
                    _codex_features
                    ;;
                login)
                    _codex_login
                    ;;
                logout)
                    _codex_logout
                    ;;
                mcp-server)
                    _codex_mcp_server
                    ;;
                resume)
                    _codex_resume
                    ;;
                sandbox)
                    _codex_sandbox
                    ;;
                *)
                    _describe -t codex_opts 'codex options' codex_opts
                    _files
                    ;;
            esac
            ;;
    esac
}

# mcp subcommand completion
_codex_mcp() {
    local curcontext="$curcontext" state line
    typeset -A opt_args

    _arguments -C \
        {-c,--config}'[Override config value]:config:' \
        {-h,--help}'[Show help]' \
        '1: :->command' \
        '*::arg:->args'

    case $state in
        command)
            local -a mcp_cmds
            mcp_cmds=(
                'list:List configured MCP servers'
                'get:Show details of configured MCP server'
                'add:Add global MCP server entry'
                'remove:Remove global MCP server entry'
                'login:Authenticate to configured MCP server via OAuth'
                'logout:Remove stored OAuth credentials for server'
            )
            _describe -t mcp_cmds 'mcp commands' mcp_cmds
            ;;
        args)
            case $line[1] in
                add)
                    _arguments \
                        {-c,--config}'[Override config value]:config:' \
                        {-h,--help}'[Show help]' \
                        '*:file:_files'
                    ;;
                get)
                    _arguments \
                        {-c,--config}'[Override config value]:config:' \
                        {-h,--help}'[Show help]' \
                        '*::server:( $(codex mcp list 2>/dev/null | grep -E "^\s+\w+" | awk "{print \$1}") )'
                    ;;
                list)
                    _arguments \
                        {-c,--config}'[Override config value]:config:' \
                        {-h,--help}'[Show help]'
                    ;;
                login|logout|remove)
                    _arguments \
                        {-c,--config}'[Override config value]:config:' \
                        {-h,--help}'[Show help]' \
                        '*::server:( $(codex mcp list 2>/dev/null | grep -E "^\s+\w+" | awk "{print \$1}") )'
                    ;;
            esac
            ;;
    esac
}

# app-server subcommand completion
_codex_app_server() {
    local curcontext="$curcontext" state line
    typeset -A opt_args

    _arguments -C \
        {-c,--config}'[Override config value]:config:' \
        {-h,--help}'[Show help]' \
        '1: :->command' \
        '*::arg:->args'

    case $state in
        command)
            local -a app_server_cmds
            app_server_cmds=(
                'generate-json-schema:Generate JSON schema'
                'generate-ts:Generate TypeScript types'
            )
            _describe -t app_server_cmds 'app-server commands' app_server_cmds
            ;;
        args)
            case $line[1] in
                generate-json-schema|generate-ts)
                    _arguments \
                        {-c,--config}'[Override config value]:config:' \
                        {-h,--help}'[Show help]'
                    ;;
            esac
            ;;
    esac
}

# apply subcommand completion
_codex_apply() {
    _arguments \
        {-c,--config}'[Override config value]:config:' \
        {-h,--help}'[Show help]'
}

# cloud subcommand completion
_codex_cloud() {
    local curcontext="$curcontext" state line
    typeset -A opt_args

    _arguments -C \
        {-c,--config}'[Override config value]:config:' \
        {-h,--help}'[Show help]' \
        '1: :->command' \
        '*::arg:->args'

    case $state in
        command)
            local -a cloud_cmds
            cloud_cmds=(
                'exec:Execute cloud task'
            )
            _describe -t cloud_cmds 'cloud commands' cloud_cmds
            ;;
        args)
            case $line[1] in
                exec)
                    _arguments \
                        {-c,--config}'[Override config value]:config:' \
                        {-h,--help}'[Show help]'
                    ;;
            esac
            ;;
    esac
}

# completion subcommand completion
_codex_completion() {
    _arguments \
        {-c,--config}'[Override config value]:config:' \
        {-h,--help}'[Show help]'
}

# exec subcommand completion
_codex_exec() {
    local curcontext="$curcontext" state line
    typeset -A opt_args

    _arguments -C \
        {-c,--config}'[Override config value]:config:' \
        {-h,--help}'[Show help]' \
        '1: :->command' \
        '*::arg:->args'

    case $state in
        command)
            local -a exec_cmds
            exec_cmds=(
                'resume:Resume execution'
            )
            _describe -t exec_cmds 'exec commands' exec_cmds
            ;;
        args)
            case $line[1] in
                resume)
                    _arguments \
                        {-c,--config}'[Override config value]:config:' \
                        {-h,--help}'[Show help]'
                    ;;
            esac
            ;;
    esac
}

# features subcommand completion
_codex_features() {
    local curcontext="$curcontext" state line
    typeset -A opt_args

    _arguments -C \
        {-c,--config}'[Override config value]:config:' \
        {-h,--help}'[Show help]' \
        '1: :->command' \
        '*::arg:->args'

    case $state in
        command)
            local -a features_cmds
            features_cmds=(
                'list:List feature flags'
            )
            _describe -t features_cmds 'features commands' features_cmds
            ;;
        args)
            case $line[1] in
                list)
                    _arguments \
                        {-c,--config}'[Override config value]:config:' \
                        {-h,--help}'[Show help]'
                    ;;
            esac
            ;;
    esac
}

# login subcommand completion
_codex_login() {
    local curcontext="$curcontext" state line
    typeset -A opt_args

    _arguments -C \
        {-c,--config}'[Override config value]:config:' \
        {-h,--help}'[Show help]' \
        '1: :->command' \
        '*::arg:->args'

    case $state in
        command)
            local -a login_cmds
            login_cmds=(
                'status:Show login status'
            )
            _describe -t login_cmds 'login commands' login_cmds
            ;;
        args)
            case $line[1] in
                status)
                    _arguments \
                        {-c,--config}'[Override config value]:config:' \
                        {-h,--help}'[Show help]'
                    ;;
            esac
            ;;
    esac
}

# logout subcommand completion
_codex_logout() {
    _arguments \
        {-c,--config}'[Override config value]:config:' \
        {-h,--help}'[Show help]'
}

# mcp-server subcommand completion
_codex_mcp_server() {
    _arguments \
        {-c,--config}'[Override config value]:config:' \
        {-h,--help}'[Show help]'
}

# resume subcommand completion
_codex_resume() {
    _arguments \
        {-c,--config}'[Override config value]:config:' \
        {-h,--help}'[Show help]'
}

# sandbox subcommand completion
_codex_sandbox() {
    local curcontext="$curcontext" state line
    typeset -A opt_args

    _arguments -C \
        {-c,--config}'[Override config value]:config:' \
        {-h,--help}'[Show help]' \
        '1: :->command' \
        '*::arg:->args'

    case $state in
        command)
            local -a sandbox_cmds
            sandbox_cmds=(
                'linux:Linux sandbox'
                'macos:macOS sandbox'
                'windows:Windows sandbox'
            )
            _describe -t sandbox_cmds 'sandbox commands' sandbox_cmds
            ;;
        args)
            case $line[1] in
                linux|macos|windows)
                    _arguments \
                        {-c,--config}'[Override config value]:config:' \
                        {-h,--help}'[Show help]'
                    ;;
            esac
            ;;
    esac
}

# Complete programming languages
_codex_languages() {
    local -a languages
    languages=(
        'python:Python'
        'javascript:JavaScript'
        'typescript:TypeScript'
        'java:Java'
        'cpp:C++'
        'c:C'
        'go:Go'
        'rust:Rust'
        'ruby:Ruby'
        'php:PHP'
        'swift:Swift'
        'kotlin:Kotlin'
        'shell:Shell/Bash'
        'sql:SQL'
        'html:HTML'
        'css:CSS'
    )
    _describe -t languages 'programming languages' languages
}

# Register completion functions
compdef _codex codex
compdef _codex cdx

# Add common aliases
alias cdx='codex'
alias cdxa='codex ask'
alias cdxc='codex chat'
alias cdxe='codex explain'
alias cdxf='codex fix'
alias cdxr='codex review'
alias cdxt='codex test'
alias cdxrf='codex refactor'
alias cdxcfg='codex config'
